In [1]:
import numpy as np

In [2]:
# 0D 
a = np.array(10)
a

array(10)

In [3]:
# 1D
a = np.array([10,20,30])
print(a)
a.shape

[10 20 30]


(3,)

In [4]:
# 2D
a = np.array([[10,20,30],[40,50,60]])
a

array([[10, 20, 30],
       [40, 50, 60]])

In [5]:
# 3D
a = np.array([[[10,20,30],[40,50,60]],[[10,20,30],[40,50,60]]])
a

array([[[10, 20, 30],
        [40, 50, 60]],

       [[10, 20, 30],
        [40, 50, 60]]])

In [6]:
list_num = [[10,20],[30,40]]
a = np.asarray(list_num)
a

array([[10, 20],
       [30, 40]])

In [7]:
a = np.zeros(4,dtype="int")
a

array([0, 0, 0, 0])

In [8]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
a = np.full((2,3),7)
a

array([[7, 7, 7],
       [7, 7, 7]])

In [10]:
a = np.full((2,3,4),7)
print(a)

[[[7 7 7 7]
  [7 7 7 7]
  [7 7 7 7]]

 [[7 7 7 7]
  [7 7 7 7]
  [7 7 7 7]]]


In [11]:
a = np.random.rand(2,4)
a

array([[0.8308541 , 0.52825693, 0.63132863, 0.36715521],
       [0.5643158 , 0.55954577, 0.75654722, 0.54442741]])

In [12]:
a = np.random.randint(2,10)
a

3

In [13]:
a = np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [14]:
a = np.eye(5,dtype="int")
print(a)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [15]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
a = np.arange(1,12,2)
a

array([ 1,  3,  5,  7,  9, 11])

In [17]:
a.reshape(2,3)

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [18]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
print(a.reshape(2,5,1))
a.shape

[[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]]]


(10,)

In [20]:
print(a.reshape(1,10))
a.shape

[[ 1  2  3  4  5  6  7  8  9 10]]


(10,)

In [21]:
print(a.reshape(-1,1))
a.shape

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]


(10,)

In [22]:
a.reshape(1,-1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
a = np.linspace(1,10,5)
a

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [24]:
a = np.linspace(1,10,5,endpoint=False)
a

array([1. , 2.8, 4.6, 6.4, 8.2])

In [25]:
a = np.arange(10,100,10)
a = a.reshape(3,3)
print(a)
print(a.shape)
print(np.size(a))

[[10 20 30]
 [40 50 60]
 [70 80 90]]
(3, 3)
9


In [26]:
a = np.array([[10,34,634],[123,564,34]])
print(a)
np.sort(a,axis=0)

[[ 10  34 634]
 [123 564  34]]


array([[ 10,  34,  34],
       [123, 564, 634]])

In [27]:
a = np.array([1,2,3])
b = np.array([5,6,7])
print(a)
print(b)

[1 2 3]
[5 6 7]


In [28]:
print(np.stack((a,b),axis=0))

[[1 2 3]
 [5 6 7]]


In [29]:
print(np.stack((a,b),axis=1))

[[1 5]
 [2 6]
 [3 7]]


In [30]:
np.vstack((a,b))

array([[1, 2, 3],
       [5, 6, 7]])

In [31]:
np.dstack((a,b))

array([[[1, 5],
        [2, 6],
        [3, 7]]])

In [32]:
np.hstack((a,b))

array([1, 2, 3, 5, 6, 7])

In [33]:
import pandas as pd

In [34]:
df = pd.read_csv("adult.csv")

In [35]:
df.head()

age         workclass  fnlwgt  education  education-num  \
0   39         State-gov   77516  Bachelors             13   
1   50  Self-emp-not-inc   83311  Bachelors             13   
2   38           Private  215646    HS-grad              9   
3   53           Private  234721       11th              7   
4   28           Private  338409  Bachelors             13   

       marital-status         occupation   relationship   race     sex  \
0       Never-married       Adm-clerical  Not-in-family  White    Male   
1  Married-civ-spouse    Exec-managerial        Husband  White    Male   
2            Divorced  Handlers-cleaners  Not-in-family  White    Male   
3  Married-civ-spouse  Handlers-cleaners        Husband  Black    Male   
4  Married-civ-spouse     Prof-specialty           Wife  Black  Female   

   capitalGain  capitalLoss  hoursPerWeek  nativeCountry income  
0         2174            0            40  United-States  <=50K  
1            0            0            13  United-States  <=50K  
2            0            0            40  United-States  <=50K  
3            0            0            40  United-States  <=50K  
4            0            0            40           Cuba  <=50K

In [36]:
df[["age","sex"]]

age     sex
0       39    Male
1       50    Male
2       38    Male
3       53    Male
4       28  Female
...    ...     ...
32556   27  Female
32557   40    Male
32558   58  Female
32559   22    Male
32560   52  Female

[32561 rows x 2 columns]

In [37]:
"""for rec in df.iterrows():
    print(rec)"""

'for rec in df.iterrows():\n    print(rec)'

In [38]:
df.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education-num',
       'marital-status', 'occupation', 'relationship', 'race', 'sex',
       'capitalGain', 'capitalLoss', 'hoursPerWeek', 'nativeCountry',
       'income'],
      dtype='object')

In [41]:
df.loc[2:5,["age","fnlwgt"]]

age  fnlwgt
2   38  215646
3   53  234721
4   28  338409
5   37  284582

In [1]:
import numpy as np
import tensorflow as tf
import torch as t

2025-12-08 14:05:26.517680: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
a = t.tensor(1)
a

tensor(1)

In [6]:
t.tensor([[1,2]])

tensor([[1, 2]])

In [13]:
tf.constant([[12,3221]])

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[  12, 3221]], dtype=int32)>

In [14]:
t.zeros(2)

tensor([0., 0.])

In [15]:
t.zeros([1,2])

tensor([[0., 0.]])

In [31]:
t.zeros([2,3],dtype=t.int64).reshape(3,2)

tensor([[0, 0],
        [0, 0],
        [0, 0]])

In [28]:
a = np.zeros([2,3])

In [21]:
#tf.zeros([4,5,3])

In [25]:
np.shape(a)

(4, 2, 3)

In [29]:
a.reshape(3,2)

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [35]:
np.reshape(a,[3,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [36]:
b = t.zeros([2,3])

In [37]:
t.reshape(b,[3,2])

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [42]:
 b = tf.zeros([2,3])

In [43]:
tf.reshape(b,[3,2])

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [44]:
a = np.linspace(10,20,9)
a

array([10.  , 11.25, 12.5 , 13.75, 15.  , 16.25, 17.5 , 18.75, 20.  ])

In [77]:
a = np.array([1])
b = np.array([2])
np.concatenate([a,b])

array([1, 2])

In [78]:
np.split(a,[2,3])
np.min(a)

np.int64(1)

In [81]:
a = np.array([[1, 2], [3, 4]])
>>> b = np.array([[5, 6],[7,8]])
>>> np.concatenate((a, b), axis=0)
np.min(a,axis=1)

array([1, 3])

In [56]:
np.concat((a,b),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [70]:
a = tf.zeros([2,3])
b = tf.zeros([2,3])

In [74]:
tf.split(a,2)

[<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0., 0., 0.]], dtype=float32)>,
 <tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0., 0., 0.]], dtype=float32)>]

AttributeError: module 'tensorflow' has no attribute 'min'

In [65]:
tf.concat([a,b],0)

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [120]:
a = t.zeros([2,3])
b = t.zeros([2,3])

In [122]:
t.concat([a,b],dim=1)

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [123]:
t.sum(a)

tensor(0.)

In [106]:
a = t.tensor([[1,2],[3,4]],dtype=t.float32)
a

tensor([[1., 2.],
        [3., 4.]])

In [102]:
a[:,1]

tensor([2, 4])

In [119]:
t.transpose(a,0,1)

tensor([[1., 3.],
        [2., 4.]])

In [118]:
t.randn(2,3)

tensor([[-1.0260,  1.0770, -0.1462],
        [-0.9819,  0.5144, -0.8930]])

In [117]:
np.random.rand(2,3)

array([[0.26197686, 0.06186471, 0.53262372],
       [0.32413813, 0.82474695, 0.10170828]])

In [124]:
a = tf.constant(2)
b = tf.constant(3)

In [125]:
a+b

<tf.Tensor: shape=(), dtype=int32, numpy=5>