In [45]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

In [46]:
dataset = pd.read_csv("/home/majji-vinaykumar/Documents/Data.csv")
dataset.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [47]:
dataset.shape

(9568, 5)

In [48]:
dataset.isna().sum()

AT    0
V     0
AP    0
RH    0
PE    0
dtype: int64

# Creating Feature Matrix and Dependent Variable

In [49]:
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1:].values
print(X,y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]] [[463.26]
 [444.37]
 [488.56]
 ...
 [429.57]
 [435.74]
 [453.28]]


In [50]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.2, random_state=0)

# Feature Scaling

In [51]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)
y_train = sc.fit_transform(y_train)

In [73]:
y_test

array([[431.23],
       [460.01],
       [461.14],
       ...,
       [473.26],
       [438.  ],
       [463.28]])

In [53]:
from sklearn.svm import SVR
regressor = SVR(kernel='rbf') #rbf means noninear
regressor.fit(x_train,y_train)

/usr/lib/python3/dist-packages/sklearn/utils/validation.py:1300: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

In [54]:
y_pred =regressor.predict(x_test)

In [55]:
y_pred

array([-1.18727339,  0.21311322,  0.39445405, ...,  0.9556216 ,
       -0.87278266,  0.38779571])

In [63]:
y_pred =  y_pred.reshape(-1, 1)

In [64]:
y_pred

array([[-1.18727339],
       [ 0.21311322],
       [ 0.39445405],
       ...,
       [ 0.9556216 ],
       [-0.87278266],
       [ 0.38779571]])

In [65]:
y_pred = sc.inverse_transform(y_pred)

In [66]:
y_pred

array([[434.05242921],
       [457.93810186],
       [461.03113894],
       ...,
       [470.60268461],
       [439.41653548],
       [460.91757115]])

In [70]:
y_pred = y_pred.reshape(1,-1)

In [71]:
y_pred

array([[434.05242921, 457.93810186, 461.03113894, ..., 470.60268461,
        439.41653548, 460.91757115]])

In [72]:
from sklearn.metrics import r2_score
print(r2_score(y_test,y_pred))

ValueError: Found input variables with inconsistent numbers of samples: [1914, 1]